package br.com.corelabs.npsharpfx.frontend.theme.mobile

import android.graphics.Color

data class ThemeModel(
    val id: String,
    val assetName: String,
    val name: String,
    val type: String,

    val background: Int,
    val surface: Int,
    val surfaceElevated: Int,
    val card: Int,
    val cardHover: Int,
    val cardPressed: Int,
    val primary: Int,
    val secondary: Int,
    val accent: Int,
    val error: Int,
    val warning: Int,
    val success: Int,
    val text: Int,
    val textMuted: Int,
    val textDisabled: Int,
    val border: Int,
    val focusBorder: Int,
    val divider: Int,

    val titleBarBackground: Int,
    val titleBarForeground: Int,
    val navBarBackground: Int,
    val navBarForeground: Int,
    val navBarActive: Int,
    val sideBarBackground: Int,
    val sideBarForeground: Int,
    val sideBarBorder: Int,
    val statusBarBackground: Int,
    val statusBarForeground: Int,

    val buttonBackground: Int,
    val buttonForeground: Int,
    val buttonHover: Int,
    val buttonPressed: Int,
    val menuBackground: Int,
    val menuForeground: Int,
    val menuHover: Int,
    val tabActiveBackground: Int,
    val tabActiveForeground: Int,
    val tabInactiveBackground: Int,
    val tabInactiveForeground: Int,
    val tabBorder: Int,

    val editorBackground: Int,
    val editorForeground: Int,
    val editorGutterBackground: Int,
    val editorLineNumber: Int,
    val editorActiveLineNumber: Int,
    val editorSelection: Int,
    val editorSelectionInactive: Int,
    val editorCursor: Int,
    val editorCurrentLine: Int,

    val terminalBackground: Int,
    val terminalForeground: Int,
    val terminalCursor: Int,
    val terminalSelection: Int,
    val terminalAnsiBlack: Int,
    val terminalAnsiRed: Int,
    val terminalAnsiGreen: Int,
    val terminalAnsiYellow: Int,
    val terminalAnsiBlue: Int,
    val terminalAnsiMagenta: Int,
    val terminalAnsiCyan: Int,
    val terminalAnsiWhite: Int,
    val terminalAnsiBrightBlack: Int,
    val terminalAnsiBrightRed: Int,
    val terminalAnsiBrightGreen: Int,
    val terminalAnsiBrightYellow: Int,
    val terminalAnsiBrightBlue: Int,
    val terminalAnsiBrightMagenta: Int,
    val terminalAnsiBrightCyan: Int,
    val terminalAnsiBrightWhite: Int,

    val syntaxKeyword: Int,
    val syntaxType: Int,
    val syntaxComment: Int,
    val syntaxString: Int,
    val syntaxNumber: Int,
    val syntaxFunction: Int,
    val syntaxVariable: Int,
    val syntaxConstant: Int,
    val syntaxPunctuation: Int,
    val syntaxInvalid: Int,

    val scrollbarTrack: Int,
    val scrollbarThumb: Int,
    val scrollbarThumbHover: Int,
    val selectionText: Int,

    val borderRadius: Float,
    val cardRadius: Float,
    val buttonRadius: Float,
    val inputRadius: Float,
    val blur: Boolean,
    val shadow: Boolean,
    val transparentEditor: Boolean,
    val wallpaperOpacity: Float,
    val elevation: Float,
    val animationDurationMs: Long,
    val animationEasing: String
) {
    fun terminalAnsiColors(): IntArray = intArrayOf(
        terminalAnsiBlack,
        terminalAnsiRed,
        terminalAnsiGreen,
        terminalAnsiYellow,
        terminalAnsiBlue,
        terminalAnsiMagenta,
        terminalAnsiCyan,
        terminalAnsiWhite,
        terminalAnsiBrightBlack,
        terminalAnsiBrightRed,
        terminalAnsiBrightGreen,
        terminalAnsiBrightYellow,
        terminalAnsiBrightBlue,
        terminalAnsiBrightMagenta,
        terminalAnsiBrightCyan,
        terminalAnsiBrightWhite
    )

    companion object {
        @JvmField
        val Default = ThemeModel(
            id = "nps-dark",
            assetName = "dark.json",
            name = "NPSharp Dark",
            type = "dark",
            background = Color.rgb(0, 0, 0),
            surface = Color.rgb(24, 24, 24),
            surfaceElevated = Color.rgb(31, 31, 31),
            card = Color.rgb(30, 30, 30),
            cardHover = Color.rgb(43, 43, 43),
            cardPressed = Color.rgb(55, 55, 55),
            primary = Color.rgb(0, 122, 204),
            secondary = Color.rgb(86, 156, 214),
            accent = Color.rgb(255, 216, 0),
            error = Color.rgb(244, 71, 71),
            warning = Color.rgb(229, 192, 123),
            success = Color.rgb(106, 153, 85),
            text = Color.rgb(245, 245, 245),
            textMuted = Color.rgb(150, 150, 150),
            textDisabled = Color.rgb(102, 102, 102),
            border = Color.rgb(45, 45, 45),
            focusBorder = Color.rgb(255, 216, 0),
            divider = Color.rgb(35, 35, 35),
            titleBarBackground = Color.rgb(24, 24, 24),
            titleBarForeground = Color.rgb(245, 245, 245),
            navBarBackground = Color.rgb(24, 24, 24),
            navBarForeground = Color.rgb(205, 205, 205),
            navBarActive = Color.rgb(255, 216, 0),
            sideBarBackground = Color.rgb(0, 0, 0),
            sideBarForeground = Color.rgb(220, 220, 220),
            sideBarBorder = Color.rgb(45, 45, 45),
            statusBarBackground = Color.rgb(13, 13, 13),
            statusBarForeground = Color.WHITE,
            buttonBackground = Color.rgb(37, 37, 38),
            buttonForeground = Color.rgb(245, 245, 245),
            buttonHover = Color.rgb(45, 45, 48),
            buttonPressed = Color.rgb(62, 62, 66),
            menuBackground = Color.rgb(30, 30, 30),
            menuForeground = Color.rgb(245, 245, 245),
            menuHover = Color.rgb(45, 45, 48),
            tabActiveBackground = Color.rgb(0, 0, 0),
            tabActiveForeground = Color.rgb(245, 245, 245),
            tabInactiveBackground = Color.rgb(24, 24, 24),
            tabInactiveForeground = Color.rgb(150, 150, 150),
            tabBorder = Color.rgb(45, 45, 45),
            editorBackground = Color.rgb(0, 0, 0),
            editorForeground = Color.rgb(220, 220, 220),
            editorGutterBackground = Color.rgb(0, 0, 0),
            editorLineNumber = Color.rgb(133, 133, 133),
            editorActiveLineNumber = Color.rgb(220, 220, 220),
            editorSelection = Color.rgb(38, 79, 120),
            editorSelectionInactive = Color.rgb(63, 63, 63),
            editorCursor = Color.rgb(255, 216, 0),
            editorCurrentLine = Color.rgb(20, 20, 20),
            terminalBackground = Color.rgb(0, 0, 0),
            terminalForeground = Color.rgb(220, 220, 220),
            terminalCursor = Color.rgb(255, 216, 0),
            terminalSelection = Color.rgb(38, 79, 120),
            terminalAnsiBlack = Color.rgb(0, 0, 0),
            terminalAnsiRed = Color.rgb(205, 49, 49),
            terminalAnsiGreen = Color.rgb(13, 188, 121),
            terminalAnsiYellow = Color.rgb(229, 229, 16),
            terminalAnsiBlue = Color.rgb(36, 114, 200),
            terminalAnsiMagenta = Color.rgb(188, 63, 188),
            terminalAnsiCyan = Color.rgb(17, 168, 205),
            terminalAnsiWhite = Color.rgb(229, 229, 229),
            terminalAnsiBrightBlack = Color.rgb(102, 102, 102),
            terminalAnsiBrightRed = Color.rgb(241, 76, 76),
            terminalAnsiBrightGreen = Color.rgb(35, 209, 139),
            terminalAnsiBrightYellow = Color.rgb(245, 245, 67),
            terminalAnsiBrightBlue = Color.rgb(59, 142, 234),
            terminalAnsiBrightMagenta = Color.rgb(214, 112, 214),
            terminalAnsiBrightCyan = Color.rgb(41, 184, 219),
            terminalAnsiBrightWhite = Color.WHITE,
            syntaxKeyword = Color.rgb(86, 156, 214),
            syntaxType = Color.rgb(78, 201, 176),
            syntaxComment = Color.rgb(106, 153, 85),
            syntaxString = Color.rgb(206, 145, 120),
            syntaxNumber = Color.rgb(181, 206, 168),
            syntaxFunction = Color.rgb(220, 220, 170),
            syntaxVariable = Color.rgb(156, 220, 254),
            syntaxConstant = Color.rgb(100, 102, 149),
            syntaxPunctuation = Color.rgb(212, 212, 212),
            syntaxInvalid = Color.rgb(244, 71, 71),
            scrollbarTrack = Color.TRANSPARENT,
            scrollbarThumb = Color.argb(95, 127, 127, 127),
            scrollbarThumbHover = Color.argb(140, 127, 127, 127),
            selectionText = Color.WHITE,
            borderRadius = 4f,
            cardRadius = 4f,
            buttonRadius = 4f,
            inputRadius = 5f,
            blur = false,
            shadow = true,
            transparentEditor = false,
            wallpaperOpacity = 0f,
            elevation = 8f,
            animationDurationMs = 220L,
            animationEasing = "fastOutSlowIn"
        )
    }
}
